#include "BleKeyboard.h"
#include "HIDTypes.h"
#include <algorithm>

#define KID 1
#define MID 2
#define MOID 3
static const uint8_t keyboardMap[] PROGMEM={USAGE_PAGE(1),1,USAGE(1),6,COLLECTION(1),1,REPORT_ID(1),KID,USAGE_PAGE(1),7,USAGE_MINIMUM(1),0xe0,USAGE_MAXIMUM(1),0xe7,LOGICAL_MINIMUM(1),0,LOGICAL_MAXIMUM(1),1,REPORT_SIZE(1),1,REPORT_COUNT(1),8,HIDINPUT(1),2,REPORT_COUNT(1),1,REPORT_SIZE(1),8,HIDINPUT(1),1,REPORT_COUNT(1),6,REPORT_SIZE(1),8,LOGICAL_MINIMUM(1),0,LOGICAL_MAXIMUM(1),0x65,USAGE_MINIMUM(1),0,USAGE_MAXIMUM(1),0x65,HIDINPUT(1),0,END_COLLECTION(0),USAGE_PAGE(1),0x0c,USAGE(1),1,COLLECTION(1),1,REPORT_ID(1),MID,USAGE_PAGE(1),0x0c,USAGE_MINIMUM(1),0,USAGE_MAXIMUM(1),1,REPORT_SIZE(1),1,REPORT_COUNT(1),16,USAGE(1),0xb5,USAGE(1),0xb6,USAGE(1),0xb7,USAGE(1),0xcd,USAGE(1),0xe2,USAGE(1),0xe9,USAGE(1),0xea,USAGE(2),0x23,2,USAGE(2),0x94,1,USAGE(2),0x92,1,USAGE(2),0x2a,2,USAGE(2),0x21,2,USAGE(2),0x26,2,USAGE(2),0x24,2,USAGE(2),0x83,1,USAGE(2),0x8a,1,HIDINPUT(1),2,END_COLLECTION(0)};
static const uint8_t compositeMap[] PROGMEM={
#include "composite_descriptor.inc"
};
static uint8_t ascii(uint8_t c,bool& shift){ shift=false; if(c>='a'&&c<='z')return c-'a'+4; if(c>='A'&&c<='Z'){shift=true;return c-'A'+4;} if(c>='1'&&c<='9')return c-'1'+0x1e; if(c=='0')return 0x27; if(c==' ')return 0x2c; const char* chars="-=[]\\;'/.,`"; const uint8_t codes[]={0x2d,0x2f,0x30,0x31,0x31,0x33,0x34,0x38,0x36,0x37,0x35}; for(uint8_t i=0;i<sizeof(codes);++i)if(c==chars[i])return codes[i]; if(c=='\n')return 0x28; if(c=='\t')return 0x2b; return 0;}
static void configureSecurity(){ BLESecurity* sec=new BLESecurity(); sec->setAuthenticationMode(ESP_LE_AUTH_BOND); sec->setCapability(ESP_IO_CAP_NONE); sec->setInitEncryptionKey(ESP_BLE_ENC_KEY_MASK|ESP_BLE_ID_KEY_MASK); sec->setRespEncryptionKey(ESP_BLE_ENC_KEY_MASK|ESP_BLE_ID_KEY_MASK); }
BleKeyboard::BleKeyboard(std::string n,std::string m,uint8_t b):name(n.substr(0,15)),manufacturer(m.substr(0,15)),battery(b){}
void BleKeyboard::setup(const uint8_t* map,size_t len,uint8_t appearance){ BLEDevice::init(String(name.c_str())); BLEServer* s=BLEDevice::createServer(); s->setCallbacks(this); hid=new BLEHIDDevice(s); keyboard=hid->inputReport(KID); output=hid->outputReport(KID); media=hid->inputReport(MID); keyboard->setAccessPermissions(ESP_GATT_PERM_READ|ESP_GATT_PERM_WRITE); media->setAccessPermissions(ESP_GATT_PERM_READ|ESP_GATT_PERM_WRITE); output->setCallbacks(this); hid->manufacturer()->setValue(String(manufacturer.c_str())); hid->pnp(0x02,vid,pid,version); hid->hidInfo(0,1); configureSecurity(); hid->reportMap((uint8_t*)map,len); hid->startServices(); advertising=s->getAdvertising(); advertising->setAppearance(appearance); advertising->addServiceUUID(hid->hidService()->getUUID()); advertising->setScanResponse(false); advertising->start(); hid->setBatteryLevel(battery); }
void BleKeyboard::begin(){setup(keyboardMap,sizeof(keyboardMap),HID_KEYBOARD);}
void BleKeyboard::end(){if(advertising)advertising->stop(); connected=false;}
bool BleKeyboard::isConnected()const{return connected;} void BleKeyboard::setBatteryLevel(uint8_t b){battery=std::min<uint8_t>(100,b);if(hid)hid->setBatteryLevel(battery);} void BleKeyboard::setName(std::string n){name=n.substr(0,15);} void BleKeyboard::setDelay(uint32_t d){delayMs=d;} void BleKeyboard::set_vendor_id(uint16_t v){vid=v;} void BleKeyboard::set_product_id(uint16_t v){pid=v;} void BleKeyboard::set_version(uint16_t v){version=v;}
void BleKeyboard::notify(BLECharacteristic* c,const uint8_t* d,size_t n){if(connected&&c){c->setValue(d,n);c->notify();if(delayMs)delay(delayMs);}}
void BleKeyboard::sendReport(KeyReport*r){notify(keyboard,(uint8_t*)r,sizeof(*r));} void BleKeyboard::sendReport(MediaKeyReport*r){notify(media,(uint8_t*)r,sizeof(*r));}
size_t BleKeyboard::press(uint8_t k){bool sh=false;if(k>=128){if(k<136)report.modifiers|=1<<(k-128);else k-=136;}else{k=ascii(k,sh);if(!k){setWriteError();return 0;}if(sh)report.modifiers|=2;} if(k){for(uint8_t i=0;i<6;i++)if(report.keys[i]==k)return 1;for(uint8_t i=0;i<6;i++)if(!report.keys[i]){report.keys[i]=k;sendReport(&report);return 1;}setWriteError();return 0;}sendReport(&report);return 1;}
size_t BleKeyboard::release(uint8_t k){bool sh=false;if(k>=128){if(k<136)report.modifiers&=~(1<<(k-128));else k-=136;}else{k=ascii(k,sh);if(!k)return 0;if(sh)report.modifiers&=~2;}if(k)for(auto &key:report.keys)if(key==k)key=0;sendReport(&report);return 1;}
size_t BleKeyboard::press(const MediaKeyReport k){mediaReport[0]|=k[0];mediaReport[1]|=k[1];sendReport(&mediaReport);return 1;} size_t BleKeyboard::release(const MediaKeyReport k){mediaReport[0]&=~k[0];mediaReport[1]&=~k[1];sendReport(&mediaReport);return 1;} void BleKeyboard::releaseAll(){memset(&report,0,sizeof(report));memset(mediaReport,0,sizeof(mediaReport));sendReport(&report);sendReport(&mediaReport);} size_t BleKeyboard::write(uint8_t c){size_t n=press(c);release(c);return n;} size_t BleKeyboard::write(const MediaKeyReport c){size_t n=press(c);release(c);return n;} size_t BleKeyboard::write(const uint8_t*b,size_t n){size_t w=0;while(n--)if(*b!='\r'){w+=write(*b);b++;}else b++;return w;}
void BleKeyboard::onConnect(BLEServer*){connected=true;releaseAll();} void BleKeyboard::onDisconnect(BLEServer*){connected=false;if(advertising)advertising->start();} void BleKeyboard::onWrite(BLECharacteristic*){}

BleMouse::BleMouse(std::string n,std::string m,uint8_t b):name(n.substr(0,15)),manufacturer(m.substr(0,15)),battery(b){}
static const uint8_t mouseMap[]={USAGE_PAGE(1),1,USAGE(1),2,COLLECTION(1),1,REPORT_ID(1),MOID,USAGE(1),1,COLLECTION(1),0,USAGE_PAGE(1),9,USAGE_MINIMUM(1),1,USAGE_MAXIMUM(1),5,LOGICAL_MINIMUM(1),0,LOGICAL_MAXIMUM(1),1,REPORT_COUNT(1),5,REPORT_SIZE(1),1,HIDINPUT(1),2,REPORT_COUNT(1),1,REPORT_SIZE(1),3,HIDINPUT(1),1,USAGE_PAGE(1),1,USAGE(1),0x30,USAGE(1),0x31,USAGE(1),0x38,USAGE_PAGE(1),0x0c,USAGE(2),0x38,2,LOGICAL_MINIMUM(1),0x81,LOGICAL_MAXIMUM(1),0x7f,REPORT_SIZE(1),8,REPORT_COUNT(1),4,HIDINPUT(1),6,END_COLLECTION(0),END_COLLECTION(0)};
void BleMouse::begin(){BLEDevice::init(String(name.c_str()));BLEServer*s=BLEDevice::createServer();s->setCallbacks(this);hid=new BLEHIDDevice(s);input=hid->inputReport(MOID);hid->manufacturer()->setValue(String(manufacturer.c_str()));hid->pnp(2,0x05ac,0x820b,0x0210);hid->hidInfo(0,1);configureSecurity();hid->reportMap((uint8_t*)mouseMap,sizeof(mouseMap));hid->startServices();advertising=s->getAdvertising();advertising->setAppearance(HID_MOUSE);advertising->addServiceUUID(hid->hidService()->getUUID());advertising->setScanResponse(false);advertising->start();hid->setBatteryLevel(battery);} void BleMouse::end(){if(advertising)advertising->stop();connected=false;} bool BleMouse::isConnected()const{return connected;} void BleMouse::setBatteryLevel(uint8_t b){battery=std::min<uint8_t>(100,b);if(hid)hid->setBatteryLevel(battery);} void BleMouse::setName(std::string n){name=n.substr(0,15);} void BleMouse::notify(){if(connected&&input){input->setValue((uint8_t*)&report,sizeof(report));input->notify();delay(2);}} void BleMouse::move(signed char x,signed char y,signed char wheel,signed char hWheel){report.x=x;report.y=y;report.wheel=wheel;report.hWheel=hWheel;notify();report.x=report.y=report.wheel=report.hWheel=0;} void BleMouse::scrollUp(signed char amount){move(0,0,amount,0);} void BleMouse::scrollDown(signed char amount){move(0,0,-amount,0);} void BleMouse::scrollLeft(signed char amount){move(0,0,0,-amount);} void BleMouse::scrollRight(signed char amount){move(0,0,0,amount);} void BleMouse::click(uint8_t b){press(b);release(b);} void BleMouse::press(uint8_t b){report.buttons|=b;notify();} void BleMouse::release(uint8_t b){report.buttons&=~b;notify();} void BleMouse::releaseAll(){report.buttons=0;notify();} void BleMouse::onConnect(BLEServer*){connected=true;} void BleMouse::onDisconnect(BLEServer*){connected=false;if(advertising)advertising->start();}

BleComposite::BleComposite(std::string n,std::string m,uint8_t b):BleKeyboard(n,m,b){}
void BleComposite::begin(){BLEDevice::init(String(name.c_str()));BLEServer*s=BLEDevice::createServer();s->setCallbacks(this);hid=new BLEHIDDevice(s);keyboard=hid->inputReport(KID);output=hid->outputReport(KID);media=hid->inputReport(MID);mouseInput=hid->inputReport(MOID);output->setCallbacks(this);hid->manufacturer()->setValue(String(manufacturer.c_str()));hid->pnp(2,vid,pid,version);hid->hidInfo(0,1);configureSecurity();hid->reportMap((uint8_t*)compositeMap,sizeof(compositeMap));hid->startServices();advertising=s->getAdvertising();advertising->setAppearance(HID_KEYBOARD);advertising->addServiceUUID(hid->hidService()->getUUID());advertising->setScanResponse(false);advertising->start();hid->setBatteryLevel(battery);}
void BleComposite::mouseNotify(){if(connected&&mouseInput){mouseInput->setValue((uint8_t*)&mouseReport,sizeof(mouseReport));mouseInput->notify();delay(2);}} void BleComposite::move(signed char x,signed char y,signed char w,signed char h){mouseReport.x=x;mouseReport.y=y;mouseReport.wheel=w;mouseReport.hWheel=h;mouseNotify();mouseReport.x=mouseReport.y=mouseReport.wheel=mouseReport.hWheel=0;} void BleComposite::scrollUp(signed char amount){move(0,0,amount,0);} void BleComposite::scrollDown(signed char amount){move(0,0,-amount,0);} void BleComposite::scrollLeft(signed char amount){move(0,0,0,-amount);} void BleComposite::scrollRight(signed char amount){move(0,0,0,amount);} void BleComposite::click(uint8_t b){mousePress(b);mouseRelease(b);} void BleComposite::mousePress(uint8_t b){mouseReport.buttons|=b;mouseNotify();} void BleComposite::mouseRelease(uint8_t b){mouseReport.buttons&=~b;mouseNotify();} void BleComposite::mouseReleaseAll(){mouseReport.buttons=0;mouseNotify();} bool BleComposite::mouseConnected()const{return connected;}
